# Generated by Django 5.0.4 on 2024-08-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='user_id',
            new_name='user',
        ),
    ]
