# Generated by Django 5.0.4 on 2024-08-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_user_id_organization_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'verbose_name': 'User Type', 'verbose_name_plural': 'User Types'},
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_type',
        ),
    ]
